server:
  port: 8081 # Config server test? ??? ??

spring:
  application:
    name: config-server-test # ?? ??????? ??

  # spring cloud config ?? ?? ??
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yaejinkong/config-repository.git # ?? ??? ??? Git ???? ??(URL)
          default-label: main # ?? ???
          timeout: 5 # ?? ??? ? ???? ?????? ???? ??